name: Update KenPom CSV

# Trigger every day at 10 AM UTC and allow manual trigger
on:
  schedule:
    - cron: '0 10 * * *'   # Runs at 10:00 AM UTC daily
  workflow_dispatch:       # Allows manual trigger

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the scraper
      - name: Run KenPom scraper
        run: python scrape_kenpom.py

      # Step 5: Commit updated CSV
      - name: Commit updated CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git diff --quiet && echo "No changes to commit" || git commit -m "Update KenPom CSV"
          git push
